exports.data = [
    { name: "Lionel Messi", rank: 1, team: "Barcelona" },
    { name: "Virgil van Dijk", rank: 2, team: "Liverpool" },
    { name: "Sadio Mané", rank: 3, team: "Liverpool" },
    { name: "Cristiano Ronaldo", rank: 4, team: "Juventus" },
    { name: "Mohamed Salah", rank: 5, team: "Liverpool" },
    { name: "Kylian Mbappé", rank: 6, team: "Paris Saint-Germain" },
    { name: "Robert Lewandowski", rank: 7, team: "Bayern Munich" },
    { name: "Raheem Sterling", rank: 8, team: "Manchester City" },
    { name: "Alisson", rank: 9, team: "Liverpool" },
    { name: "Frenkie de Jong", rank: 10, team: "Barcelona" },
    { name: "Roberto Firmino", rank: 11, team: "Liverpool" },
    { name: "Kevin de Bruyne", rank: 12, team: "Manchester City" },
    { name: "Sergio Agüero", rank: 13, team: "Manchester City" },
    { name: "Eden Hazard", rank: 14, team: "Real Madrid" },
    { name: "Harry Kane", rank: 15, team: "Tottenham Hotspur" },
    { name: "Bernardo Silva", rank: 16, team: "Manchester City" },
    { name: "Trent Alexander-Arnold", rank: 17, team: "Liverpool" },
    { name: "Matthijs de Ligt", rank: 18, team: "Juventus" },
    { name: "Son Heung-min", rank: 19, team: "Tottenham Hotspur" },
    { name: "Karim Benzema", rank: 20, team: "Real Madrid" },
    { name: "Marc-André ter Stegen", rank: 21, team: "Barcelona" },
    { name: "N'Golo Kanté", rank: 22, team: "Chelsea" },
    { name: "Andrew Robertson", rank: 23, team: "Liverpool" },
    { name: "Jan Oblak", rank: 24, team: "Atlético Madrid" },
    { name: "Antoine Griezmann", rank: 25, team: "Barcelona" },
    { name: "Luis Suárez", rank: 26, team: "Barcelona" },
    { name: "Dusan Tadic", rank: 27, team: "Ajax" },
    { name: "Pierre-Emerick Aubameyang", rank: 28, team: "Arsenal" },
    { name: "Hakim Ziyech", rank: 29, team: "Ajax" },
    { name: "Kalidou Koulibaly", rank: 30, team: "Napoli" },
    { name: "Neymar", rank: 31, team: "Paris Saint-Germain" },
    { name: "Jadon Sancho", rank: 32, team: "Borussia Dortmund" },
    { name: "Donny van de Beek", rank: 33, team: "Ajax" },
    { name: "Fabinho", rank: 34, team: "Liverpool" },
    { name: "João Félix", rank: 35, team: "Atlético Madrid" },
    { name: "Sergio Ramos", rank: 36, team: "Real Madrid" },
    { name: "Joshua Kimmich", rank: 37, team: "Bayern Munich" },
    { name: "Serge Gnabry", rank: 38, team: "Bayern Munich" },
    { name: "Ángel Di María", rank: 39, team: "Paris Saint-Germain" },
    { name: "Ederson", rank: 40, team: "Machester City" },
    { name: "Christian Eriksen", rank: 41, team: "Tottenham Hotspur" },
    { name: "Paulo Dybala", rank: 42, team: "Juventus" },
    { name: "Georginio Wijnaldum", rank: 43, team: "Liverpool" },
    { name: "Toni Kroos", rank: 44, team: "Real Madrid" },
    { name: "Luka Modric", rank: 45, team: "Real Madrid" },
    { name: "David Silva", rank: 46, team: "Manchester City" },
    { name: "Lautaro Martínez", rank: 47, team: "Internazionale" },
    { name: "Jamie Vardy", rank: 48, team: "Leicester City" },
    { name: "Riyad Mahrez", rank: 49, team: "Manchester City" },
    { name: "Miralem Pjanic", rank: 50, team: "Juventus" },
    { name: "Romelu Lukaku", rank: 51, team: "Internazionale" },
    { name: "Gabriel Barbosa", rank: 52, team: "Flamengo" },
];